sPHENIX-Collaboration/ProdFlow

RHIC2023/CALOR/scripts/run_calorimeter.sh, RHIC2023/CALOR/yaml/runEventCombine.yaml
Reverts sPHENIX-Collaboration/ProdFlow#1
=> Revert "Dev"

RHIC2023/CALOR/macros/Fun4All_Combiner.C
That should take care of empty files stalling processing
=> check for missing or empty lists and do not load them

RHIC2023/CALOR/macros/drawProdQA.C, RHIC2023/CALOR/macros/drawProdTrackingQA.C
Adds scripts to compare the number of DSTs at each stage of production. Run with parameters first run number, last run number, production tag, build tag.
=> Add production stage comparison scripts

RHIC2023/CALOR/macros/calo_production_event_number.py
Add script to find production event numbers for calo datasets. Ratios and plots of rundb event numbers and production dst event numbers are included.
=> Calo production event number stats and plot maker

.gitignore, run2auau/TrackingProduction/Fun4All_Job0.C, run2auau/TrackingProduction/Fun4All_JobA.C, run2auau/TrackingProduction/Fun4All_JobC.C, run2auau/TrackingProduction/Fun4All_SingleTrkrHitSet_Unpacker.C, run2auau/TrackingProduction/Fun4All_TrkrHitSet_Unpacker.C, run2auau/TrackingProduction/GetEntries.C, run2auau/TrackingProduction/run.sh, run2auau/TrackingProduction/run_job0.sh, run2auau/TrackingProduction/run_jobA.sh, run2auau/TrackingProduction/run_jobC.sh, run2auau/TrackingProduction/stageout.sh, run2auau/cosmics/Fun4All_SingleStream_Combiner.C, run2auau/cosmics/Fun4All_Stream_Combiner.C, run2auau/cosmics/GetEntries.C, run2auau/cosmics/run_cosmics.sh, run2auau/cosmics/stageout.sh
Adds the tracking macros for triggered mode in AuAu
=> feat: Add AuAu tracking macros

run2auau/TriggerProduction/Fun4All_Prdf_Combiner.C, run2auau/cosmics/Fun4All_Stream_Combiner.C, run2pp/TriggerProduction/Fun4All_Prdf_Combiner.C, run2pp/cosmics/Fun4All_Stream_Combiner.C
This PR adds a safeguard against running without input lists
=> Missing input safeguard

run2auau/CaloProduction/Fun4All_HCalCosmics.C, run2auau/CaloProduction/Fun4All_Year2.C, run2auau/CaloProduction/Fun4All_Year2_Calib.C, run2auau/CaloProduction/Fun4All_Year2_Fitting.C, run2auau/CaloProduction/GetEntries.C, run2auau/CaloProduction/run.sh, run2auau/CaloProduction/runy2.sh, run2auau/CaloProduction/runy2calib.sh, run2auau/CaloProduction/runy2fitting.sh, run2auau/CaloProduction/stageout.sh
copied the macros from run2pp and updated the Fun4All_Year2_Calib.C with AuAu specific settings
=> add run2auau calo macros

run2auau/JetProduction/Fun4All_JetProductionYear2_AuAu.C
This PR adds a jet macro specifically geared towards Year2 AuAu data production.
=> Add Year 2 AuAu Jet Macro

run2pp/TrackingProduction/Fun4All_JobA.C, run2pp/TrackingProduction/Fun4All_JobC.C
Updates the seeding macro and track fitting macro to the latest and greatest
=> fix: Seeding update

run2pp/cosmics/Fun4All_SingleStream_Combiner.C
Use time frame reader, per Jin's suggestions
=> feat: use time frame reader

run2pp/cosmics/Fun4All_SingleStream_Combiner.C
Adds a dbtag argument for the QA
=> feat: add dbtag arg

run2auau/CaloProduction/Fun4All_Year2_Fitting.C, run2auau/CaloProduction/runy2fitting.sh
Update the fitting pass in Au+Au area
=> add the fitting QA for auau as well

run2auau/CaloProduction/stageout.sh, run2auau/JetProduction/stageout.sh, run2auau/TrackingProduction/stageout.sh, run2auau/TriggerProduction/stageout.sh, run2auau/mbd_calib/stageout.sh, run2auau/streaming/stageout.sh, run2pp/CaloProduction/stageout.sh, run2pp/DST_STREAMING_EVENT_run2pp_new_2024p009.yaml, run2pp/JetProduction/stageout.sh, run2pp/TrackingProduction/stageout.sh, run2pp/TriggerProduction/stageout.sh, run2pp/mbd_calib/stageout.sh, run2pp/streaming/run_parallel_streams.sh, run2pp/streaming/stageout.sh
Applies new naming convention, directory structure.  And confirms that streaming event building is operable.
=> Dev new naming

run2auau/streaming/Fun4All_SingleStream_Combiner.C, run2auau/streaming/Fun4All_Stream_Combiner.C, run2pp/streaming/Fun4All_SingleStream_Combiner.C, run2pp/streaming/Fun4All_Stream_Combiner.C
Updates all the event combining macros to read from the db to set the bco ranges for the INTT as in 
https://github.com/sPHENIX-Collaboration/macros/pull/1040
=> feat: auto trig/stream mode for intt

run2pp/JetProduction/Fun4All_JetSkimmedProductionYear2.C
pull the latest jetskimmer macro from the macro repo
=> skimmer update

run2pp/JetProduction/runy2jetskim.sh
The Jet Skimmer pass should read in CALOFITTING and output DST_JET and DST_JETCALO
=> correct output name

run2auau/TrackingProduction/Fun4All_Job0.C, run2auau/TrackingProduction/run_job0.sh, run2pp/CaloProduction/Fun4All_Year2_Fitting.C, run2pp/JetProduction/Fun4All_JetSkimmedProductionYear2.C, run2pp/JetProduction/runy2jetskim.sh, run2pp/TrackingProduction/Fun4All_Job0.C, run2pp/TrackingProduction/Fun4All_SingleJob0.C, run2pp/TrackingProduction/run_job0.sh
Reverts sPHENIX-Collaboration/ProdFlow#68
... intended to go into the prod_triggered branch, not streaming.
=> Revert "Updating the production branch before running DST_CALOFITTING_ana462_2024p010"

run2pp/streaming/Fun4All_SingleStream_Combiner.C, run2pp/streaming/run_parallel_streams.sh
This adds the production of segmentized QA histos to the event combining. This won't work until we have an ana build for this [PR](https://github.com/sPHENIX-Collaboration/coresoftware/pull/3381) so we should hold off on merging it until that is through
=> feat: segmentized histos

run2auau/streaming/Fun4All_SingleStream_Combiner.C, run2auau/streaming/run_parallel_streams.sh
Updates the run2auau macro and script to the latest and greatest for processing purposes
=> update run2auau macro and script

run2auau/TrackingProduction/Fun4All_SingleJob0.C, run2auau/TrackingProduction/run_singlejob0.sh, run2pp/TrackingProduction/run_singlejob0.sh
Adds the single job 0 workflow pieces to the auau area and the script for running the pp jobs
=> fix: clean up single job 0 workflow

run2auau/DST_STREAMING_EVENT_run2auau_ana464_2024p010.yaml, run2auau/DST_STREAMING_EVENT_run2auau_ana466_2024p012.yaml, run2pp/DST_STREAMING_EVENT_run2pp_ana464_2024p011.yaml, run2pp/DST_STREAMING_EVENT_run2pp_ana466_2024p012.yaml
This adds a few yaml files that have been used to produce the most recent stable auau and pp streaming data
=> add yaml files

run2pp/TrackingProduction/Fun4All_SingleJob0.C, run2pp/TrackingProduction/run_singlejob0.sh
Trying to get clustering production going
=> remove laser clustering and add python setup

run2pp/TrackingProduction/Fun4All_JobA.C, run2pp/TrackingProduction/Fun4All_SingleJob0.C, run3auau/TrackingProduction/Fun4All_JobA.C, run3auau/TrackingProduction/Fun4All_JobC.C, run3auau/TrackingProduction/Fun4All_SingleJob0.C
This updates all of the run3auau macros to function with the new dbtag
=> update: run3auau macros

run3auau/streaming/run_parallel_streams.sh
Adds the histogram stageout call since the macro no longer handles this for online production
=> fix: add histogram stageout

run3auau/TrackingProduction/Fun4All_JobC.C
Fixes the macro to properly run the silicon-TPC QA
=> fix: silicon-tpc qa

run3auau/CaloProduction/runy2fitting.sh, run3auau/streaming/Fun4All_SingleStream_Combiner.C
Fixes the production of the streaming qa files
=> Streaming qa fix

run3auau/TrackingProduction/Fun4All_Job0.C, run3auau/TrackingProduction/Fun4All_SingleJob0.C
Addition of TpcLaserQA module. Requires https://github.com/sPHENIX-Collaboration/coresoftware/pull/3518
=> Addition of TpcLaserQA module

run3auau/CaloProduction/runy2calib.sh
dump the QA file to ./ so that the script can find it for stageout
=> Update runy2calib.sh: extract base name

run2pp/TriggerProduction/Fun4All_New_Prdf_Combiner.C
Fun4All_New_Prdf_Combiner.C runs the new combiner
=> add new combiner

run2pp/streaming/Fun4All_SingleStream_Combiner.C, run3auau/TrackingProduction/Fun4All_JobA.C, run3auau/TrackingProduction/Fun4All_JobC.C, run3auau/TrackingProduction/Fun4All_SingleJob0.C, run3auau/streaming/Fun4All_SingleStream_Combiner.C
Downscales the verbosity appropriately in the tracking macros
=> Downscale verbosity

run3auau/streaming/Fun4All_SingleStream_Combiner.C
The raw hit containers need to now have an ebdc_packet format
=> fix:use ebdc_packet format

run3auau/TrackingProduction/Fun4All_SingleJob0.C
Fixes the hit unpacking for 48 nodes
=> fix: hit unpacking for 48 nodes

short/run3auau/tracking_code/Fun4All_SingleJob0.C
This makes the clustering job more flexible with missing tpc files to deal better with the upstream decoder issues
=> fix: flexibility with missing files

run2pp/TrackingProduction/Fun4All_JobC.C, run2pp/TrackingProduction/run_jobC.sh
Adds the track fit and vertex qa to the production macro and corresponding script
=> feat: fit and vertex qa

short/run3auau/tracking_code/Fun4All_JobA.C, short/run3auau/tracking_code/Fun4All_SingleJob0.C
Reverts sPHENIX-Collaboration/ProdFlow#143 for being stupid
=> Revert "fix: remove output dsts"

run2pp/TrackingProduction/Fun4All_SingleJob0.C
Run mvtx clustering with standard function
=> fix: mvtx clusterizer call
