run2auau/TrackingProduction/Fun4All_Job0.C
run2auau/TrackingProduction/Fun4All_JobA.C
run2auau/TrackingProduction/Fun4All_JobC.C
run2pp/TrackingProduction/Fun4All_Job0.C
run2pp/TrackingProduction/Fun4All_JobA.C
run2pp/TrackingProduction/Fun4All_JobC.C

Updated laser event rejection using a new module, exact same changes made for run2pp and run2auau tracking. Global flag (G4TPC::REJECT_LASER_EVENTS) in macros turns on/off the rejection everywhere (default is on)
In job 0, laser event identification and laser clustering must be done before tpc clustering. Tpc clustering will also return EVENT_OK if flag is true. In jobs A and C, new rejection module is called by new function in Trkr_Reco.C only if flag is true, and will return ABORTEVENT, skipping all further reconstruction for that event.
Requires https://github.com/sPHENIX-Collaboration/coresoftware/pull/3204 and https://github.com/sPHENIX-Collaboration/macros/pull

Laser Event Rejection

---

run2auau/cosmics/Fun4All_SingleStream_Combiner.C
run2auau/cosmics/Fun4All_Stream_Combiner.C
run2pp/cosmics/Fun4All_SingleStream_Combiner.C
run2pp/cosmics/Fun4All_Stream_Combiner.C

The MVTX BCO range is now automatically set based on the strobe width extracted from the daqdb
https://github.com/sPHENIX-Collaboration/coresoftware/pull/3211

feat: mvtx bco range automatically set

---

run2pp/cosmics/Fun4All_SingleStream_Combiner.C

The upstream yaml file handles the prdf label, the current implementation confuses the handling of the stageout script

fix: remove prdf label

---

run2auau/DST_CALIBRATIONS_run2auau.yaml
run2auau/DST_STREAMING_EVENT_run2auau_new_2024p007.yaml
run2auau/DST_TRIGGERED_EVENT_run2auau_new_2024p007.yaml
run2auau/DST_TRIGGERED_EVENT_run2auau_vernierscan_new_2024p007.yaml
run2auau/JetProduction/runjets.sh
run2auau/TriggerProduction/run.sh
run2auau/TriggerProduction/runvs.sh
run2cosmics/DST_TRIGGERED_EVENT_run2cosmics_ana444_2024p007.yaml
run2pp/DST_CALIBRATIONS_run2pp.yaml
run2pp/DST_STREAMING_EVENT_run2pp_ana439_2024p007.yaml
run2pp/DST_STREAMING_EVENT_run2pp_ana441_2024p007.yaml
run2pp/DST_TRIGGERED_EVENT_run2pp_ana437_2024p007.yaml
run2pp/DST_TRIGGERED_EVENT_run2pp_ana444_2024p007.yaml
run2pp/DST_TRIGGERED_EVENT_run2pp_new_2024p007.yaml
run2pp/DST_TRKR_CLUSTERS_run2pp_ana449_2024p008.yaml
run2pp/JetProduction/runjets.sh
run2pp/TriggerProduction/run.sh

Alma 9 support in slurp uses a common job wrapper.  The system passes the name of the user's production 
script as the first argument, and appends the production status id (aka 'cupsid') as the last argument.  
It relies on being able to stage in the user's production script, which is part of the list of
files to be 'rsync'ed into the job.  This requires us to pass the directory from which we 
submitted the job (PWD) and the list of files (rsync) to be specified in the list of arguments
in the condor job block.
Ideally the system would manage this, but the place where we should append this information does not
have easy access to the PWD...  I need to spend some time to sort out why.  The easiest way to get this in production is to append these by hand in the workflow files. 
We don't …

Update workflows for alma9

---

run2auau/TrackingProduction/Fun4All_Job0.C
run2auau/TrackingProduction/run_job0.sh
run2pp/TrackingProduction/Fun4All_Job0.C
run2pp/TrackingProduction/run_job0.sh

New calls to lamination fitting in job0 for both run2pp and run2auau. This will perform the lamination fitting and write the resulting histograms to a file with the same name as the DST with "Laminations_" prepended. These files will be inputs in later jobs for the distortion corrections.
This PR requires changes made in coresoftware (https://github.com/sPHENIX-Collaboration/coresoftware/pull/3301) and macros (https://github.com/sPHENIX-Collaboration/macros/pull/1023)

Lamination Fitting

---

run2pp/streaming/Fun4All_Stream_Combiner.C

Updates the combined combiner to use the time frame reader instead of the pooler

fix: use time frame reader

---

run2pp/TrackingProduction/Fun4All_SingleJob0.C

The single job0 macro had some wrong ordering of modules which was causing it to not work. This fixes it and removes some no longer needed code

fix: single job0 macro crash

---

run2pp/TrackingProduction/Fun4All_JobA.C

Updates the pp seeding macro get prepared for a seeding DST production attempt
1. Clean up 
2. Turn on reject laser event flag
3. Enable static distortion correction map, which we can confidently say improves the track residuals in the TPC
4. Update silicon-tpc track matching windows
5. Enable strobe by strobe seeding in the silicon

fix: update seeding macro

---

run2pp/TrackingProduction/Fun4All_JobA.C
run2pp/TrackingProduction/Fun4All_JobC.C

This moves the track matching into job C and updates the seeding modules. This should allow us to run a seeding production and punt all the calibration applications to the end.

feat: seeding update

---

run2pp/TrackingProduction/Fun4All_JobA.C

This adds a cut in on the max number of seeds to avoid events where the seeder goes awry

fix: add max seeds cut

---

run2pp/TrackingProduction/Fun4All_JobA.C
run2pp/TrackingProduction/Fun4All_JobC.C
run2pp/TrackingProduction/Fun4All_SingleJob0.C

This updates the jobC macro to use new improved vertexing cuts given the current state of the alignment and to also propagate the tracks back to the vertex position for much improved DCA resolution.
It also adds the GL1RAWHIT node to the output DST for all jobs, so that it is persistent and one can always access the trigger bit regardless of what DST they are looking at.
Also removes the misalignment factors, which tests show are no longer necessary

fix: update vertexing in jobc

---

run2pp/TrackingProduction/Fun4All_JobC.C

Enables the flags to use the shifted MVTX geometry in jobc

fix: use shifted mvtx geometry in jobc

---

run3auau/streaming/Fun4All_SingleStream_Combiner.C

This returns the online macro to producing a single QA file, which will be easier in handling in the offline qa world

refactor: single bco qa file

---

run3auau/streaming/Fun4All_SingleStream_Combiner.C

This fixes the event combining qa to run after End is called, which inadvertently got moved when removing the segmentized histogramming

fix: streaming qa file production

---

run3auau/CaloProduction/runy2calib.sh

The input name right now for the online production is a absolute path(for example: /sphenix/lustre01/sphnxpro/production/run3auau/cosmics/new_2025p000_v000/DST_CALOFITTING/run_00061900_00062000/dst/DST_CALOFITTING_run3auau_new_2025p000_v000-00061985-00290.root)
only replace the first instance of the string won't change the file name properly. This PR replaces all

Update filename string replacement in runy2calib.sh

---

run2auau/TrackingProduction/Fun4All_SingleJob0.C
run2pp/TrackingProduction/Fun4All_SingleJob0.C
run3auau/TrackingProduction/Fun4All_Job0.C
run3auau/TrackingProduction/Fun4All_SingleJob0.C

Adds laser QA to production for run3auau. Also fixes some issues with run2pp and run2auau where in some cases laser clusters were not generated not written to DST, likewise for lamination clusters

Laser QA and fixes

---

run2auau/streaming/Fun4All_SingleStream_Combiner.C
run2pp/streaming/Fun4All_SingleStream_Combiner.C
run3auau/streaming/Fun4All_SingleStream_Combiner.C

This applies a downscale of 1000 to the event wise printouts in the Fun4All_SingleStream_Combiner.C macros. Feel free to use this in other macros

apply 1k downscale to event wise printouts

---

run3auau/streaming/Fun4All_SingleStream_Combiner.C

Adds the runnumber flag to the streaming macro for the INTT bco range lookup

fix: add runnumber flag

---

run3auau/streaming/Fun4All_SingleStream_Combiner.C

The macros will now quit if no streaming readout input manager is registered, preventing infinite loops and just running over the gl1

quite if no streaming subsystem is registered

---

run2pp/TriggerProduction/Fun4All_New_Prdf_Combiner.C

This PR updates the Fun4All_New_Prdf_Combiner macro. Now mbd and gl1 packets are kept during subsequent processing through the fitting. The default splitting leads to a huge memory consumption when reading the produced DSTs. The split level is not set in the macro to be zero (no splitting), reducing the memory needs by about a factor of 5

reduce memory for DST readback via split level, keep mbd and gl1 packets

---

run3auau/short/streaming_code/Fun4All_SingleStream_Combiner.C

@kkauder Here is the PR, it just needed a node name fix to deal with the ebdc00_0, ebdc00_1... filename types instead of the previous ebdc00, ebdc01... filename types

fix: switch to 48 file node name

---

run3auau/TrackingProduction/Fun4All_SingleJob0.C

Fixed issue that was skipping segment *39 due to issue with identifying TPOT ebdc. Instead of identifying TPC files as ones that contain "ebdc" but not ones that contain "39", still identify as containing "ebdc" but don't include ones that contain "ebdc39"

Fix TPC unpacking skipping segment *39

---

short/run3auau/streaming_code/Fun4All_SingleStream_Combiner.C

Adds the runnumber/segment to the file name scheme for the calibration files, which was mistakenly left off

fix: calib filename scheme

---

short/run3auau/tracking_code/Fun4All_JobA.C
short/run3auau/tracking_code/Fun4All_SingleJob0.C

Comment out the dst output manager so that output DSTs are not written for downstream reconstruction right now

fix: remove output dsts

---

run2pp/TrackingProduction/Fun4All_JobC.C

Oops. As the title says, I left some global variable uses in one of the functions. This was happy in my own version but the production will complain. @osbornjd this can be merged

CD: Forgot to copy over global variables to locl
